# Hyprpaper Config

# wallpaper = DP-1, /home/cbreare/Pictures/WallPaper/Bing-Light the way-Andreas Kunz-Getty Images.jpg

# preload = /home/cbreare/Pictures/WallPaper/Bing-Light the way-Andreas Kunz-Getty Images.jpg
