# Hyprpaper Config

wallpaper = DP-2, /media/Drives/DS2/HOME/Media/Pictures/WallPaper/Bing-Light the way-Andreas Kunz-Getty Images.jpg

preload = /media/Drives/DS2/HOME/Media/Pictures/WallPaper/Bing-Light the way-Andreas Kunz-Getty Images.jpg
