# Hyprpaper Config

wallpaper = DP-1, /home/cbreare/Pictures/WallPaper/Bing-Adriatic heights-Ilija Ascic-Shutterstock.jpg

preload = /home/cbreare/Pictures/WallPaper/Bing-Adriatic heights-Ilija Ascic-Shutterstock.jpg
