-- Generated by HyprMod

-- Settings
hl.config({
    cursor = {
        inactive_timeout = 10.0,
    },
    decoration = {
        blur = {
            enabled = false,
        },
        dim_inactive = false,
        shadow = {
            enabled = false,
        },
    },
    general = {
        extend_border_grab_area = 4,
        layout = "dwindle",
        resize_on_border = true,
        snap = {
            enabled = false,
        },
    },
    input = {
        sensitivity = 0.0,
    },
    misc = {
        focus_on_activate = true,
        key_press_enables_dpms = true,
        mouse_move_enables_dpms = true,
    },
})

-- Bezier curves
hl.curve("feel", { type = "bezier", points = { {0.0, 1.0}, {0.0, 1.0} } })

-- Animations
hl.animation({
    leaf = "global",
    enabled = true,
    speed = 5.0,
    bezier = "feel",
})

-- Monitors
hl.monitor({
    output = "DP-2",
    mode = "3440x1440@165.00Hz",
    position = "0x0",
    scale = 1,
    vrr = 0,
    sdrbrightness = 0.5,
    sdr_min_luminance = 0.07,
    sdr_max_luminance = 1000,
    min_luminance = 0.07,
    max_luminance = 604,
    max_avg_luminance = 604,
})
